version: '3.3'
services:
  featurebar:
    container_name: featurebar
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    #ports:
    #  - "5001:5000"
